plugins {
    id 'java'
    id 'net.neoforged.moddev' version '2.0.141'
}

version = '0.5.3'
group = 'com.example.helpfulworkers'
base { archivesName = 'helpfulworkers' }

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    version = '21.1.235'
    runs {
        client { client() }
        uiTest {
            client()
            gameDirectory = file('run/uitest')
            systemProperty 'helpfulworkers.uiTest', 'true'
        }
        server { server() }
        gameTestServer {
            type = "gameTestServer"
            systemProperty 'neoforge.enabledGameTestNamespaces', 'helpfulworkers'
            gameDirectory = file('run/gametest')
        }
    }
    mods { helpfulworkers { sourceSet sourceSets.main } }
}

tasks.withType(JavaCompile).configureEach { options.encoding = 'UTF-8' }
tasks.named('runServer') { standardInput = System.in }
